### ISSUE TITLE
Can Not Access Vectr Web Application

### ISSUE THREAD

**Issue by rezasarvani** [SecurityRiskAdvisors/VECTR#106]
Hi, after executing "docker-compose up- d" everything says "Done", but when i go to "vector.local:8081" (Changed the host in .env file) nothing is showing and i face:
'''This site can’t be reached!
Check if there is a typo in vector.local.
DNS_PROBE_FINISHED_NXDOMAIN'''

**Comment by rezasarvani** [comment]
Distributor ID: Kali
Description: Kali GNU/Linux Rolling
Release: 2020.3
Codename: kali-rolling

**Comment by SRAPSpencer** [comment]
Have you edited your hosts file? 

Editing the .env file tells VECTR where to expect connections from, but it doesn't tell your computer where vectr.local is. We recommend for testing purposes editing your hosts file to allow for DNS resolution.

**Comment by rezasarvani** [comment]
Thanks A Lot For Your Quick Response
I'm trying to access it using the same machine (Kali Linux), can you help me what to add in my /etc/resolve.conf?

**Comment by SRAPSpencer** [comment]
Resolve.conf is for editing nameservers and DNS servers.

Since this instance is running locally on your machine you should edit the /etc/hosts file. If you have changed your .env to vector from vectr it should be something like.

127.0.0.1 vector.local

Once you save and exit you should be able to reach the application. Again this is only for testing purposes, for a production deployment it should be setup with proper DNS resolution on a supported platform.

**Comment by rezasarvani** [comment]
Thanks A Looot For your Help <3
Closing The Issue...

**Comment by Ekonoiss123** [comment]
I can't log in on Vectr !
They say to verify my e-mail, but when I click on the box they ask me to make a new account.
I need my existing account because I already have many works on there !
Could somebody please help me ?

**Comment by SRAPSpencer** [comment]
> I can't log in on Vectr ! They say to verify my e-mail, but when I click on the box they ask me to make a new account. I need my existing account because I already have many works on there ! Could somebody please help me ?

You should open a new issue for this and provide the appropriate information.
