### ISSUE TITLE
feature: improve stix2.1 or stix2.0 compatibility

### ISSUE THREAD

**Issue by highkay** [SecurityRiskAdvisors/VECTR#109]
I import several stix2 json and have no luck.
[stix2.zip](https://github.com/SecurityRiskAdvisors/VECTR/files/5818336/stix2.zip)

**Comment by carlvonderheid** [comment]
For clarity, these used to work in a previous build, or you're trying them for the first time?

**Comment by thebleucheese** [comment]
VECTR doesn't currently support STIX 2.1 and there aren't currently plans to support it. Our reference is the MITRE enterprise-attack.json CTI format which contains enough information to build Test Cases and Campaigns from the threat intelligence data. They're still using STIX 2.0. The apt1.json and poisonivy.json do not contain traditional MITRE ATT&CK attack pattern data. Instead, they're using a proprietary format that doesn't match the MITRE heatmap. Unfortunately, we will not be able to support files in this format. 

The "2021-01-14T09_57_09.980Z_TLP_ALL" file is mostly IOC data and doesn't contain enough information about attack patterns to build Test Cases in VECTR.  

The remaining "Iranian_TTP_Bundle_010920.json" should import successfully since it's in VECTR's native export format. We'll investigate to see if there are import issues with that file.  

Thanks - we'll try to provide some more documentation on how the STIX 2.0 import works in the future. It's very closely tied to MITRE's CTI format since raw STIX 2.0 can be very vague or incomplete.
