### ISSUE TITLE
Alarm assesment question.

### ISSUE THREAD

**Issue by Evelynn90** [SecurityRiskAdvisors/VECTR#115]
Greetings,

I'm working into deploying alarm assesment and I've deployed a RedCanary host. However, I'm not pretty sure on how to import the results form the assesment into Vectr.

I've seen that i'm available to import yaml and json files but it works only for Att&ck matrix techniques.

Does anybody know how to import assesment data from a RedCanary alarm test into Vectr?

Thanks in advance.

**Comment by SRAPSpencer** [comment]
I'm not sure exactly what type of assessment data you're trying to import from RedCanary, but it's not supported at this time. The only RedCanary affiliated data able to be imported is from AtomicRed. If you could better describe your use case we could potentially add it as a feature request to be reviewed in the future. 

Paul

**Comment by Evelynn90** [comment]
We're trying to deploy a quality assurance project within out network by launching RedCanary.

The idea is to import the logs, alarms and all the data generated into Vectr and using it as a reporting tool.

Thanks for your help any way.

Best regards,
Evelynn

**Comment by SRAPSpencer** [comment]
We're currently developing an API that will allow for reads/writes to VECTR data. This is our current plan to facilitate the various import and integration requests we've received for various other products. We don't have a firm delivery date but we do anticipate for it to be released this year. This should allow anyone to take files and write an integration so that they could be accepted by our API.

Paul

**Comment by Evelynn90** [comment]
Okay.

Seems to be a pretty good tool for the future.

Thanks for your help!
