### ISSUE TITLE
Installing Vectr in Docker for windows

### ISSUE THREAD

**Issue by mahdialibi** [SecurityRiskAdvisors/VECTR#119]
Hi, This is not an issue but a feed back
We tried to install Vectr in Docker desktop on windows :
- Installing it on windows 2019 server : does not work because of some troubles in linux containers , we don't know if it's a problem with windows 2019 server or with our GPOs
- Installing it on windows 10: work directly , until now no problem , it was easy , download the zip , decompress , modify .env file , fire up "docker-compose up -d"

we will give you feed back on upgrading procedure , and long run 

Thank you for this amazing tool

**Comment by thebleucheese** [comment]
Many of our prior warnings against windows hosts were due to our previous installation process and method for building certs. A lot of that is done inside the containers now.  It's untested on Windows hosts but may work.

One area where you may run into trouble is with the docker-compose yaml file. There's a possibility docker for windows will want named volumes, which we don't include.
