### ISSUE TITLE
Latest Atomic Red YAML import is not working - use older YAML file

### ISSUE THREAD

**Issue by thebleucheese** [SecurityRiskAdvisors/VECTR#143]
There is a known bug in the latest VECTR release where the Atomic Red YAML file import is not working with the latest index file. The YAML format was changed recently and VECTR's codebase needs to be updated to support this.

Workaround until fix is ready: Use an older version of the file from prior to August 2021 like https://github.com/redcanaryco/atomic-red-team/blob/a3e16e194fdda44805d486dc6d789dbc3dc6b0b6/atomics/Indexes/index.yaml

**Comment by clr2of8** [comment]
Yes, it looks like this PR was the culprit where it started using "null" instead of empty strings for default values because those null's get transferred as blanks when the index.yaml is generated, hence causing the problem for VECTR.

A quick PowerShell one-liner can patch up the latest index.yaml in the mean time:

`(gc $env:USERPROFILE\Downloads\index.yaml -raw) -replace "default: `n","default: ''`n" | sc $env:USERPROFILE\Downloads\index.yaml`

This assumes you downloaded index.yaml to your urser's Downloads directory

**Comment by carlvonderheid** [comment]
Thanks for the clarification and script!

**Comment by carlvonderheid** [comment]
Fixed in VECTR 7.1.9, for the Atomic Red index.yml on 9/15/2021
