### ISSUE TITLE
Campaign End-to-End View

### ISSUE THREAD

**Issue by ssnkhan** [SecurityRiskAdvisors/VECTR#20]
I have looked through the various Report / Assessment screens, but can't see how I can get to the following page?

![image](https://user-images.githubusercontent.com/11506722/57669841-48ecb380-763f-11e9-96a5-996416d74e3b.png)

(Photo 3 of 4 on https://vectr.io/security-risk-advisors-simulation/)

**Comment by thebleucheese** [comment]
That screen is still there.  Assessments -> Load Assessment Group -> then click Load on a single Campaign and you get to the escalation path view.  It adds the swim lanes if you have an Campaign with Test Cases across multiple Kill Chain Phases.  The swim lanes are currently determined by order and don't tie into the actual escalation path since there are no data points to capture it - that's a feature on our longer term roadmap.

However, one thing to note: we don't ship that specific campaign or sample detection data with the Community Edition.  Some of our more detailed campaigns are 1) used solely as QA data, 2) restricted to VECTR installations that we make available for our clients, or 3) for internal SRA use only.  The sample data that ships with VECTR's Community Edition is meant to give a good start to MITRE alignment/testing using the Atomic Red-based Test Cases and a sample of custom SRA-created Test Cases (that also often align to MITRE technique IDs).  It's also meant to show what performed Assessments are supposed to look like after you've completed testing.  We're regularly building out new content so with each major VECTR release, new Test Cases and Campaigns are added or modified.  Additionally, we're in testing with new ways to get Test Case and Campaign content to and from existing VECTR instances without requiring a version update.

We also have some videos coming soon to guide how to use the system in more detail.

**Comment by ssnkhan** [comment]
Thanks @thebleucheese. The videos will be incredibly useful, as the UI can be somewhat overwhelming, especially when starting with a blank state.

As part of the Enterprise offering, will you be loading pre-mapped (known) attacks into the tool?
