### ISSUE TITLE
cannot add detected tools to testcases

### ISSUE THREAD

**Issue by djinnsec** [SecurityRiskAdvisors/VECTR#21]
Hi, i am new to using your product, so my apologies in advanced if my lack of experience is the reason for missing this feature. 

i noticed in the pre-set databases, the Testcases of performed campaigns have the ability to set detected tools and select the severity they have triggered. these also make the tools section visible in reporting. 

however, when i want to make a new Testcase this option is not there also when revieuwing all test cases.

i have followed the steps and installed using the latest version  release and did't see any errors while upgrading the databases.

**Comment by carlvonderheid** [comment]
Thanks for reaching out!  Test Cases under Administration are meant to serve as templates, which is why fields like Status and Outcome are disabled.  Only the TestCases that were used in Assessments / Campaigns show up in reporting screens.  If you created the TestCase under Administration, then you will not be able to fill in Detection Tools or the Outcome.  

We will be releasing some videos in the next few days that will shed some light on issues like this.

**Comment by djinnsec** [comment]
Thanks for the reply i have found the way to add tools outside of test case creation under Administration
