### ISSUE TITLE
no export of evidence files 

### ISSUE THREAD

**Issue by djinnsec** [SecurityRiskAdvisors/VECTR#22]
hi, currently the zip file when exporting the evidence files is empty. 

could you advice me where this data is being stored?

**Comment by thebleucheese** [comment]
The evidence files are stored as chunked binary data in the database, it would be difficult to extract non-programmatically but you could verify that they're there by looking in the evidence.files collection of the MongoDB for your active database.

...

Just checking first - you see something like this https://imgur.com/a/6DWVkdc after you've saved a test case with evidence files in it?  Note: If you add an evidence file and click the 'X' or cancel instead of saving it won't persist.

To test this I used the 'DEMO_PURPLE_CE' database then I select 'Enterprise Purple – 2019 Q1' Assessment and loaded the 'External Port Scans' Campaign.  From there, I clicked the first Test Case that shows for me: "External - Moderate Port Scan with 10 ports, service enumeration, and NSE's" and I uploaded evidence files as shown in the image above.  I continued to add evidence files to other test cases in this campaign and others for this Assessment.

To download these I go to the Assessments screen and click download reports for that particular Assessment (Enterprise Purple - 2019) and then select 'Evidence Files Zip.'  I'm then presented with a zip file that includes all of the evidence files that are attached to my test cases.

**Comment by carlvonderheid** [comment]
@djinnsec Is this still an issue for you?

**Comment by djinnsec** [comment]
@thebleucheese  i can confirm that it is working. following your instructions above, it seems that when i open a previously saved testcase to add an evidence file, i probably need to edit some text for the change to follow through. I tested this by adding a file to the test case and reopining the testcase after saving and noticing that the file which was saved previously wasn't there any more. Than i did the same but this time I added an extra "." in one of the comment field. now the saved file persisted
