### ISSUE TITLE
Application Not Authorized to use CAS

### ISSUE THREAD

**Issue by g1ldedm1n1on** [SecurityRiskAdvisors/VECTR#25]
Using sra-vectr-runtime-5.2.5-ce.zip and following the instructions on Github, I have attempted to install Vectr multiple times on different hosts. All result in "Application Not Authorized to Use CAS" when connecting to it via port 8081.  

1. Extracted to /opt/vectr
2. Generate TLS keys
3. docker-compose -f docker-compose.yml -f devSsl.yml -p dev up -d
4. Validate that containers are running with docker ps
5. Connect to port 8081 via HTTPS

I have also tried extracting 5.2.5-ce.zip and then also running ./vectr-install.sh and followed the prompts (all checks pass), but results in the same "Application Not Authorized to Use CAS" error.

**Comment by thebleucheese** [comment]
Are you using the installer scripts or doing a manual install? The manual install is a pretty involved process.  It's do-able, but the installer scripts are recommended.  

The error you're getting is most likely caused by configuration values for the hostname not matching what you're using to access the application.  So for example if you're trying to access "vectr.mycompanyinternaldomain.com" but the installer was used and the default "sravectr.internal" hostname was selected or the VECTR runtime was manually extracted and still expects "localhost."  The auth provider uses a certificate that needs to match the hostname being used to access the application.  One more note on that: accessing directly via IP address will not work due to how the auth provider functions, it tries to verify the certificate and needs a hostname. 

If you use the installer scripts you can specify a hostname during the installation process and it will perform all the necessary changes for you.  If you're manually installing there are a few places you need to change configuration values to match the hostname you'll be using - 

app/config/auth.properties you have to change vectr.server.hostname and cas.server.url

app/cas/config/cas.properties you have to change cas.server.name and cas.server.prefix

app/cas/services/vectr-8081.json you'll want to chance serviceId as well

**Comment by nrvana** [comment]
fyi guys, i had the same issue and @thebleucheese 's suggestion of properly configuring the hostname during setup fixed the issue for me (i set this value to 'kali' running in a fresh kali install). changing the setup script to default to the value of $(hostname) may help others new to setting up the project for the first time. btw, this tool is amazing and i can't wait to play around more with it.

**Comment by Selora** [comment]
I'm had a few issues as well. I'm packaging this in a VM using Vagrant on a remote hypervisor for a quick test run and this involves a few port-forwards. 
The setup I'm using looks like this:
Browser (any host) https://localhost:8081 <-- (ssh -L 8081:localhost:8081 virtualhost) --> vagrant port-forwarding 8081:8081 to localhost (the remote hypervisor) <--  ubuntu running the whole thing using the provided docker-compose commands

Based on @thebleucheese's post, I was trying to replace every instances of "localhost" with 127.0.0.1 in the config file. After removing the anti-SSRF check in the CAS config, I ended up being able to authenticate but ending on an empty page.

_What ended up working_, however, is just to modify the line for generating the self-signed cert;
`$ openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=US/ST=NY/L=SomeLocality/O=SomeOrg/CN=localhost" -keyout /opt/vectr/config/ssl.key -out /opt/vectr/config/ssl.crt`

Checking the logs from tomcat revealed that the CAS service was unable to generate a ticket without a matching SAN or CN from the HTTPS certificate. A quick fix would be to provide a working example for the openssl one-liner.

Cheers!

**Comment by carlvonderheid** [comment]
CAS is no longer part of the application in 6.0.0
