### ISSUE TITLE
New tool is not available in test case

### ISSUE THREAD

**Issue by alowenstein** [SecurityRiskAdvisors/VECTR#42]
Hi,

I created a new vendor and tool under administration->vendors and tools (red team section)
then created a new assessment, campaign and a test case.
in the test case under attacker tools, the new tool is not available. 

Thanks.

**Comment by thebleucheese** [comment]
Confirmed that there is a feature gap here.  Tools are currently copied from Template DB only on new Database created.  Tools used to always be synched from Template DB to Local DB, but this was causing issues with tools which were intentionally removed from certain databases.

A future fix will be to provide a user interface for copying or synching selected items from Template DB to Local DB so that the user does not need to duplicate work.

**Comment by alowenstein** [comment]
Thank you. Closing.
