### ISSUE TITLE
I have a problem installing the program. How to fix it

### ISSUE THREAD

**Issue by victorgenus** [SecurityRiskAdvisors/VECTR#45]
error : for sravectr_tomcat cannot start

https://drive.google.com/drive/u/0/folders/1VG7UCtbnQm6D5UjNy8ji2xA86oDwik5D

**Comment by thebleucheese** [comment]
Can you show us the contents of your vectr docker-compose.yml and devSsl.yml files?  It looks like Docker is trying to mount an individual file as a directory or on top of something existing inside the container.  

devSsl.yml is what mounts that file, 

here's my devSsl.yml

![githubissue1](https://user-images.githubusercontent.com/30511683/72353960-e4449580-36b2-11ea-911d-eefabbd24972.png)

**Comment by victorgenus** [comment]
I try to install the program again, encountering the following problems How should I fix the problem?
![zz](https://user-images.githubusercontent.com/9099745/72415585-4e3e6700-37a7-11ea-9dfd-96c1386a09b1.png)

**Comment by victorgenus** [comment]
after I setting my devSsl.yml as you and I install tomcat
then ./vectr-install.sh again  I have problem
![Capture](https://user-images.githubusercontent.com/9099745/72422139-74b6cf00-37b4-11ea-9546-0c2056fcad34.PNG)

**Comment by thebleucheese** [comment]
There are a few small issues to correct:

1. Your linux installation does not have zip installed.  Did you install zip and unzip?  The dependency instructions here https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation---Ubuntu for ubuntu outline installing dependencies including unzip, but I think you'll need to use your package manager to install "zip" as well if it's not present.

1. After a failed installation, the VECTR installer may leave some artifacts like a Docker network in place.  You will need to use Docker's commands to stop and remove any left-over networks or containers.  'sudo docker network ls' will list networks 'sudo docker network rm <ID>' will remove a network by ID, 'sudo docker ps -a' will list all running containers, 'sudo docker stop <ID>' will stop a container by ID and 'sudo docker rm <ID>' will remove a container by ID.  


As an aside, it looks like VECTR is running based on the output above.  It may be misconfigured due to the previous failed installation, but you can try going to the URL provided at the bottom of that message to see if it works.  

There's also an installation video guide here for Ubuntu: https://www.youtube.com/watch?v=SU6ZFwVyx7E

**Comment by victorgenus** [comment]
I have problem
![Capture](https://user-images.githubusercontent.com/9099745/72486746-585f7480-383e-11ea-9c48-7d776e18432b.PNG)

**Comment by ssnkhan** [comment]
Having similar issues here -- I have installed Vectr many times now, and there appears to have been some change in the past fortnight which is causing this issue.

Using Ubuntu LTS, and following the standard install instructions with the installer script. Getting the same Tomcat/docker/network issue despite using a new VM every single time.

**Comment by thebleucheese** [comment]
What directory are you installing to?  

We made a minor tweak to the installer which could have caused an issue, but we've also seen some problems with installing to the home directory which may be unrelated.  We'll investigate, and also please see if you can install to another directory outside of the home dir.

**Comment by thebleucheese** [comment]
Please reopen if you continue to have issues - the updated installer scripts should correct this issue, and the next major VECTR release will simplify this process.
