### ISSUE TITLE
API for Adding Test Cases

### ISSUE THREAD

**Issue by getshellz** [SecurityRiskAdvisors/VECTR#60]
Would be great to have an API for at least adding test cases to a specific campaign. This can then be leveraged within tools/scripts that are created to emulate a threat or evaluate detection. Would be great for automation for testing of test cases and then validation of fixes that have been created.

**Comment by SRAPSpencer** [comment]
We currently have features that would meet these requirements on the roadmap but we have no ETA on delivery.

**Comment by pathetiq** [comment]
+1 here

API for Adding data in a test case and exporting this data in json, csv. And also a call to  specific URL with POST data with json/csv to inject or import data from other web services for automation!

**Comment by thebleucheese** [comment]
Just FYI - Our current plan is GraphQL mutations and queries rather than REST for this. We have a proof of concept implemented for querying data, it's just difficult to consume with the current authentication system.

The plan is to expose more of this after we redo some of the AuthN layer (work being done right now).  We'll be creating a configuration area in the application to manage API keys.

**Comment by carlvonderheid** [comment]
Released in 8.2.0, documentation here:
https://docs.vectr.io/graphql/#vectr-graphql-api
