### ISSUE TITLE
Authentication attempt has failed

### ISSUE THREAD

**Issue by xToad** [SecurityRiskAdvisors/VECTR#61]
Hello,
I have followed your documentation on how to install VECTR on Ubuntu. As this is only an experiment, i specified a VECTR_HOSTNAME on the .env file, and then proceeded to add it to the hosts file.
However, when i try to login with the default credentials provided in the documentation, it pops the following message:
`"Authentication attempt has failed, likely due to invalid credentials. Please verify and try again."`

Credentials used:
`User: admin
Password: 11_ThisIsTheFirstPassword_11`

Both mongodb and tomcat containers are up.
If you can give me a hand on this matter, it would be great. 
Thanks.

**Comment by thebleucheese** [comment]
Did you have any issues bringing it up the first time? Or did you try to set it up once and then start over? Or alternatively, did you change the `MONGO_INITDB_ROOT_PASSWORD` in the .env file after bringing it up?  We've seen this issue a few times because of these scenarios.  

The init root password gets set and is then permanent on the Mongo DB because of how Mongo setup their container. The result of this is that if you change the init password after first startup, it will be unable to connect to the database at all and you get authentication failures.

If this sounds at all like what's happened, a quick way to fix this if you don't yet have meaningful data in your instance is to bring down the docker containers and then delete the VECTR data directory (by default in `/var/data/sandbox1`).  Then when you restart the container it'll build up a fresh DB from scratch using the init password specified in the .env file.

Some further explanation: 
The data directory is a combination of the following two values in the .env:
```
COMPOSE_PROJECT_NAME=sandbox1
VECTR_DATA_DIR=/var/data/
```
So by default it's `/var/data/sandbox1` and this doesn't get destroyed if you try to bring up a VECTR instance, bring it down, and start again.  If there's data already in there when you start an instance the `MONGO_INITDB_ROOT_PASSWORD` value will need to be the same as it was when that data was created.

...

It gets a little bit more involved if you want to recover data and then change the `MONGO_INITDB_ROOT_PASSWORD` but we'll cross that bridge if we need to.

**Comment by xToad** [comment]
Hello,
Thanks for the quick reply. Deleting the folder and restarting the container did the trick!

Thank you!
