### ISSUE TITLE
Rapid deployment for testing purposes

### ISSUE THREAD

**Issue by tbennett6421** [SecurityRiskAdvisors/VECTR#67]
Do you guys have any plans to provide an ansible playbook that can be used to stand up a vectr.io instance for development work or rapid provisioning?

**Comment by SRAPSpencer** [comment]
Ansible deployments aren't on the roadmap at this time but it may be added. We've focused on making the deployment process as easy as possible so all users can use VECTR without a need for us to support multiple deployments. 

I did see this playbook made for 5.5.7, it should be easy to update it for 5.5.9. We haven't verified it's functionality and it is entirely community made. https://thepcn3rd.blogspot.com/2020/05/ansible-playbook-for-installing-vectrio.html

**Comment by thebleucheese** [comment]
we've improved configuration and deployment since 5.x and are comfortable with the docker-compose release package. We don't think providing further configurations as part of this project will be helpful for community users at this time so closing as complete. There may be sample cloud deployment scripts in the future, but we won't include them as part of the VECTR core repo so keep an eye on SRA's other repos or open a Discussion topic here on GitHub if interested.
