### ISSUE TITLE
Missing delete/rename functionality in multiple areas

### ISSUE THREAD

**Issue by initstring** [SecurityRiskAdvisors/VECTR#75]
Hi SRA!

Once again, thanks for your hard work. Great product, we are loving it so far.

We did notice a couple areas where can can not delete or rename items, specifically:

- Campaigns
- Kill chains
- Phases

It might be handy to have a "delete" and/or "rename" option added to these.

Thanks!

**Comment by TechByTom** [comment]
Seconded! I'd really like the ability to delete a campaign (for example, if it's cancelled, or just cloned and not used).

**Comment by carlvonderheid** [comment]
So the deletion / renaming of Kill Chains and Phases will happen in the near future.  We are moving away from delivering datasets with the software and will be allowing users to import bundles from an external repo.  Because the data we deliver might have a dependency on Kill Chains and Phases, it got too confusing to account for if the user deleted them on their instance, so we made the call to flag them as read-only.

You should be able to rename and delete campaigns.  If you click on the cog under an Assessment:
![image](https://user-images.githubusercontent.com/34772348/88954218-02956b80-d268-11ea-9948-6a8ed82cbc34.png)
it will take you to the list of campaigns, each with a red "X":
![image](https://user-images.githubusercontent.com/34772348/88954268-1ccf4980-d268-11ea-8c9e-2158de2ebc3f.png)

**Comment by initstring** [comment]
Thank you, @carlvonderheid !

**Comment by thebleucheese** [comment]
Non-system data can be edited and deleted in recent VECTR versions. System data can't be modified. We require certain pre-existing data for critical application operations such as data import so that is unlikely to change in the future. Marking as complete due to core functionality being present.
