### ISSUE TITLE
Import old DB

### ISSUE THREAD

**Issue by fuckup1337** [SecurityRiskAdvisors/VECTR#77]
Hi, i have bson and json files from an old DB. Is it possible to import it to the newest version if the old isntance is not available  anymore? 
Thanks

**Comment by SRAPSpencer** [comment]
Do you know what version they were from?

The [5.5 Migration](https://docs.vectr.io/VECTR_v5_5_Migration/) directions should tell you how to run it through our upgrade container.

**Comment by fuckup1337** [comment]
Unfortunatley I dont know. I will give it a shot and let u know if that works or not. Thx

**Comment by fuckup1337** [comment]
Could be possible it was a 5.5.X already

**Comment by SRAPSpencer** [comment]
5.5 was released in April so that should give you a good frame of reference.

If you think it's 5.5 or later data you can just put it in your vectr directory under user/mongo. For example with the default path that would be /opt/vectr/user/mongo

Note that this only works if this is the first time you start vectr. Once the first time setup is complete it no longer checks the folder.

**Comment by fuckup1337** [comment]
awesome! thanks for the quick help.

**Comment by carlvonderheid** [comment]
Were you able to import your old database?

**Comment by fuckup1337** [comment]
yup, sorry I totally forgot about the ticket. 
Thanks again!
