### ISSUE TITLE
cannot access to Dashboard - Invalid Credentials

### ISSUE THREAD

**Issue by H3rn4n5** [SecurityRiskAdvisors/VECTR#78]
Hi , i've a rare problem, i've install Vectr and when i put the default credentials its said me invalid, and i've never been login on Vectr, can you help with this?, Thanks!

User: admin
Password: 11_ThisIsTheFirstPassword_11

**Comment by thebleucheese** [comment]
Please see the note here: https://github.com/SecurityRiskAdvisors/VECTR/issues/64#issuecomment-636880907 and follow the instructions to see if that fixes the issue.

This issue is most commonly seen with non-alphanumeric MONGODB_INIT_ROOT passwords set in the .env file OR in cases where MONGODB_INIT_ROOT password has been modified in the .env after starting the container for the first time.  This variable should only ever be modified prior to VECTR creating a data directory. 

If you continue having issues after this please respond with any relevant errors from the docker logs. Those can typically be accessed by running the following command on your VECTR host:
```
sudo docker logs sandbox1_tomcat_1
```

**Comment by H3rn4n5** [comment]
Thanks for response! I install all again and its works!
