### ISSUE TITLE
Invalid service ticket - This has worked fine previously

### ISSUE THREAD

**Issue by neil-fox** [SecurityRiskAdvisors/VECTR#81]
Hi,

I have vectr up and running and have been using the platform successfully. However today i have been unable to login and continually get the message 'Invalid service ticket. It was either unrecognized or has expired.'.

Looking at other tickets and online it looks this is a network issue relating to response times:

https://github.com/SecurityRiskAdvisors/VECTR/issues/27

In the above URL it mentions the following:

"One thing you can try is add or modify the timeToKillInSeconds parameter in <vectr_app_dir>/cas/config/cas.properties (default value is 10 seconds)

cas.ticket.st.timeToKillInSeconds=120"

My installation path is 'opt/vectr/' and i don't have a folder named 'cas'. Can you please advise on how i amend the timeout?

Thanks

Neil

**Comment by thebleucheese** [comment]
Hi Neil, the docker setup has changed a lot since that ticket. I've modified the cas.properties template to allow for a longer timeout. You try putting the file in the attached zip inside this folder:

[cas.properties.tmpl.zip](https://github.com/SecurityRiskAdvisors/VECTR/files/5051021/cas.properties.tmpl.zip)
```
<VECTR_DEPLOY_DIR>/user/confdtemplates
```

Then you'll need to restart the VECTR docker containers.

It's possible that is the issue, but normally when we see the invalid service ticket it's due to a hostname, port change or something similar. Have you upgraded your VECTR instance and changed configuration recently?  

We've seen an issue like this intermittently with the latest version of CAS (our authentication layer) - just bringing the docker-compose down and back up may fix it too. In an upcoming major release we'll be removing CAS for another solution since CAS adds a lot of complexity.

**Comment by neil-fox** [comment]
Hi,

Thanks for the quick response, that has solved the issue for me.

Thanks again, really loving vectr and the atomic red team templates.

Neil
