### ISSUE TITLE
Proxy to import STIX data

### ISSUE THREAD

**Issue by radiusmk** [SecurityRiskAdvisors/VECTR#89]
Hello;

Is there any way to use a proxy to import STIX data? I tried to define the variables "http(s) _proxy" and "JAVA_OPTS" in the .env file, but it didn't work.

I confirmed that the variables were defined in the TomCat container and TomCat loaded the "JAVA_OPTS" options, but for some reason the Vectr application does not use the proxy to load STIX data.

Att.
Marco Aurelio

**Comment by thebleucheese** [comment]
Just a couple questions on this:
Are you looking to import the MITRE CTI or other STIX data from a different threat intel source?

Are you referring to the TAXII server section in the Import STIX screen?  We've only tested the import functionality with our TAXII server which has some additional functionality.  The TAXII spec has changed some since that was implemented, and we may need to take another look at it for integration with other tools. 

For right now, I'd recommend using the file upload at the bottom instead.  You can drag and drop the enterprise-attack.json STIX data from MITRE (https://github.com/mitre/cti/blob/master/enterprise-attack/enterprise-attack.json) in there and submit to continue. 

We're planning on a VECTR release in the next week or two with subtechnique support on the heatmap which will work better with the most recent version of that STIX CTI data (version 7.2).

**Comment by radiusmk** [comment]
Thanks for the answer.

Yes, I am trying to import MITER CTI and I uploaded the json file.
We are looking forward to a new version of Vectr. We want to test the subtechnique support.

The Vectr team has done a great job, congratulations!

Marco Aurélio

**Comment by thebleucheese** [comment]
Unfortunately, due to the direction taken with STIX and TAXII, it doesn't make much sense to continue maintaining VECTR TAXII integration. STIX data is commonly a large loosely structured blast of indicators with the exception of very highly relational enriched data like MITRE's CTI publications. Data is so infrequently updated in this relational format that the TAXII integration isn't necessary. Our plan is to sunset the TAXII feature since it sees very limited use, and we aren't seeing quality, actionable procedure-level data from commercial threat feeds. If the data structure in STIX threat intelligence data changes dramatically to be both more procedure-oriented (vs indicator-oriented) as well as relationally complete, we'll consider looking at TAXII again.

Closing this as won't fix for now.
