### ISSUE TITLE
Request to add PRE-ATT&CK Techniques to Test Cases

### ISSUE THREAD

**Issue by cmaloney3030** [SecurityRiskAdvisors/VECTR#93]
When adding a new Test Case, the Technique drop down currently displays the MITRE ATT&CK framework.  Would like to request the addition of the MITRE PRE-ATT&CK framework in this drop down as well.

**Comment by thebleucheese** [comment]
Hey, thanks for the feedback. The Technique dropdown has an auto-complete control, but you can enter free-form text if you want to use PRE-ATT&CK techniques. If you select something using the existing auto-completed data, it will automatically select a technique ID in the Red Team Details panel, which is how we drive the Heatmap reporting. We don't currently have plans to support detection and block reporting on PRE-ATT&CK. 

**Some background on why that's the case:**
We've tried working with the PRE-ATT&CK CTI previously, and it muddies the water with what a Test Case represents in VECTR. A VECTR Test Case matches up conceptually with a detailed atomic Procedure (a specific instance of a MITRE ATT&CK Technique) that can be emulated, executed, and practically evaluated for detection and prevention on a target network. PRE-ATT&CK techniques and CTI data haven't matched up very well with this. Things like "download branding packages for possible later use in Phishing emails" have been basically undetectable in practice. 

**Possible future support for PRE-ATT&CK in VECTR:**
In the near future we're looking at creating an Assessment Planner and PRE-ATT&CK techniques / procedures might make sense as workflow steps in the planner for an Assessment or Campaign since they're more like process documentation or guidance than they are detectable activity.  PRE-ATT&CK steps might also make sense as dependencies for a Test Case. 

We're still brainstorming and requirements gathering for this so we're open to suggestions.

**Comment by SRAPSpencer** [comment]
PRE-ATT&CK was merged into ATT&CK with 8.0. Supported for 8.0 was added in the 6.0.3 Release.
